#!/usr/bin/env node
/**
 * Generate rules/rules.js from rules/scanner-rules.json (source of truth).
 * The browser cannot read the filesystem, so the web UI imports this
 * generated module instead. Run `npm run build:rules` after editing the JSON.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const jsonPath = join(here, "..", "rules", "scanner-rules.json");
const outPath = join(here, "..", "rules", "rules.js");

const rules = JSON.parse(readFileSync(jsonPath, "utf8"));

const header = "// Generated by scripts/sync-rules.mjs — do not edit by hand.\n"
  + "// Source of truth: rules/scanner-rules.json. Run `npm run build:rules` to regenerate.\n"
  + "export const RULES_DATA = ";

writeFileSync(outPath, header + JSON.stringify(rules, null, 2) + ";\n");
console.log(`rules.js regenerated from scanner-rules.json (${rules.length} rules).`);
